'use client';

import { useState } from 'react';
import type { UseCase } from '@/types';
import { deleteAdminRecord, saveAdminRecord } from '@/lib/data/admin-api';
import { Edit, Plus, Save, Trash2, X } from 'lucide-react';

export default function UseCaseManagerClient({ initialUseCases }: { initialUseCases: UseCase[] }) {
  const [items, setItems] = useState(initialUseCases);
  const [editing, setEditing] = useState<UseCase | null>(null);
  const [open, setOpen] = useState(false);
  const [name, setName] = useState(''); const [slug, setSlug] = useState(''); const [h1, setH1] = useState(''); const [content, setContent] = useState(''); const [indexable, setIndexable] = useState(true); const [message, setMessage] = useState('');
  const reset = () => { setEditing(null); setName(''); setSlug(''); setH1(''); setContent(''); setIndexable(true); setOpen(true); };
  const edit = (item: UseCase) => { setEditing(item); setName(item.name); setSlug(item.slug); setH1(item.h1); setContent(item.content); setIndexable(item.indexable); setOpen(true); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); const record: UseCase = { id: editing?.id ?? `uc-${Date.now()}`, name: name.trim(), slug: (slug || name).toLowerCase().trim().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, ''), h1: h1.trim() || name.trim(), content: content.trim(), faq: editing?.faq ?? [], indexable }; try { const saved = await saveAdminRecord<UseCase>('use_cases', record); setItems((current) => editing ? current.map((item) => item.id === saved.id ? saved : item) : [...current, saved]); setOpen(false); setMessage('Đã lưu nhu cầu thuê.'); } catch (error) { setMessage(error instanceof Error ? error.message : 'Không thể lưu.'); } };
  const remove = async (item: UseCase) => { if (!confirm(`Xóa nhu cầu ${item.name}?`)) return; try { await deleteAdminRecord('use_cases', item.id); setItems((current) => current.filter((entry) => entry.id !== item.id)); } catch (error) { setMessage(error instanceof Error ? error.message : 'Không thể xóa.'); } };
  return <div className="space-y-5">{message && <p className="rounded-xl bg-cyan-500/10 px-4 py-3 text-sm font-bold text-cyan-300">{message}</p>}<div className="flex justify-between"><p className="text-sm text-slate-400">{items.length} nhu cầu thuê</p><button onClick={reset} className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2.5 text-xs font-black text-slate-950"><Plus className="size-4" /> Thêm nhu cầu</button></div><div className="overflow-hidden rounded-2xl border border-slate-800 bg-slate-900"><table className="w-full text-left text-xs"><thead className="border-b border-slate-800 bg-slate-950 text-slate-400"><tr><th className="px-5 py-4">Tên</th><th className="px-5 py-4">Slug</th><th className="px-5 py-4">Hiển thị</th><th className="px-5 py-4 text-right">Thao tác</th></tr></thead><tbody className="divide-y divide-slate-800">{items.map((item) => <tr key={item.id}><td className="px-5 py-4 font-black text-white">{item.name}</td><td className="px-5 py-4 font-mono text-slate-400">{item.slug}</td><td className="px-5 py-4 text-slate-300">{item.indexable ? 'Đang bật' : 'Đang tắt'}</td><td className="px-5 py-4 text-right"><button onClick={() => edit(item)} className="mr-2 rounded-lg p-2 text-sky-300"><Edit className="size-4" /></button><button onClick={() => remove(item)} className="rounded-lg p-2 text-rose-300"><Trash2 className="size-4" /></button></td></tr>)}</tbody></table></div>{open && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/70 p-4"><form onSubmit={save} className="w-full max-w-lg space-y-4 rounded-3xl border border-slate-800 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="font-black text-white">{editing ? 'Sửa nhu cầu thuê' : 'Thêm nhu cầu thuê'}</h2><button type="button" onClick={() => setOpen(false)}><X className="text-slate-400" /></button></div>{[['Tên nhu cầu', name, setName], ['Slug', slug, setSlug], ['Tiêu đề H1', h1, setH1]].map(([label, value, setter]) => <label key={label as string} className="block text-xs font-bold text-slate-400">{label as string}<input value={value as string} onChange={(event) => (setter as (value: string) => void)(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-white" /></label>)}<label className="block text-xs font-bold text-slate-400">Mô tả<textarea value={content} onChange={(event) => setContent(event.target.value)} rows={5} className="mt-1 w-full rounded-xl border border-slate-700 bg-slate-950 px-3 py-2 text-white" /></label><label className="flex items-center gap-2 text-xs font-bold text-slate-300"><input type="checkbox" checked={indexable} onChange={(event) => setIndexable(event.target.checked)} /> Hiển thị trên website</label><button className="inline-flex items-center gap-2 rounded-xl bg-cyan-500 px-4 py-2.5 text-xs font-black text-slate-950"><Save className="size-4" /> Lưu</button></form></div>}</div>;
}
